export const constant = {
	USER_LOGGED_IN: 'USER_LOGGED_IN',
	USER_LOGGED_OUT: 'USER_LOGGED_OUT',
	USER_DATA: 'USER_DATA',
	IS_REDIRECT: 'IS_REDIRECT',
	TOKEN: 'TOKEN',
	IS_LOGGED_IN: 'IS_LOGGED_IN',
	LOG_OUT: 'LOG_OUT',
	ADD_WISHLIST: 'ADD_WISHLIST',
	SET_AUTH_STEP: 'SET_AUTH_STEP',
	IS_OTP_EXPIRED: 'IS_OTP_EXPIRED',
	SET_AUTH_DATA: 'SET_AUTH_DATA',
	IS_AGREE: 'IS_AGREE',
	INITIAL: 'INITIAL',
	PHONE_NUMBER: 'PHONE_NUMBER',
	COUNTRY_CODE: 'COUNTRY_CODE',
	STORE_DATA: 'STORE_DATA',
	GET_ADDRESS: 'GET_ADDRESS',
	UPDATE_ADDRESS: 'UPDATE_ADDRESS',
	DELETE_ADDRESS: 'DELETE_ADDRESS',
	IS_EDIT_ADDRESS: 'IS_EDIT_ADDRESS',
	CURRENT_ADDRESS: 'CURRENT_ADDRESS',
	ADD_ORDER: 'ADD_ORDER',
	STORES: 'STORES',
	SET_STORE: 'SET_STORE',


	// Cart Item
	ADD_CART_ITEM: 'ADD_CART_ITEM',
	UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
	REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
	CLEAR_CART: 'CLEAR_CART',
	OPEN_CART_MODAL: 'OPEN_CART_MODAL',

	// save card
	ADD_CARD: "ADD_CARD",
	DELETE_CARD: "DELETE_CARD",

	// Add recent search
	ADD_RECENT_SEARCH: "ADD_RECENT_SEARCH",

	// cancel order
	CANCEL_ORDER: "CANCEL_ORDER"
}
